import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">The Social Integration Demo!</a>
        </h1>

        <p className={styles.description}>Let's get started...</p>

        <div className={styles.grid}>
          <a href="/dashboard" className={styles.card}>
            <h2>Twitter &rarr;</h2>
            <p>Check out Twitter Integration.</p>
          </a>

          <a href="/dashboard" className={styles.card}>
            <h2>Instagram &rarr;</h2>
            <p>Check out Instagram Integration.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Powered by MewTwo
        </a>
      </footer>
    </div>
  );
}
